### ISSUE TITLE
make_script function does not include packages

### ISSUE THREAD

**Issue by dfalster** [richfitz/remake#72]
Exporting a script with `make_script` should list packages at the top of the file, but doesn't

**Comment by richfitz** [comment]
Weird, given: https://github.com/richfitz/remake/blob/master/R/script.R#L3-L4

**Comment by aammd** [comment]
Hm, its true on my project as well.

**Comment by richfitz** [comment]
I'm guessing that `obj$store$env$packages` is returning `NULL`; I feel like I changed something in the logic there.  So:

- [ ] Add regression test that fails in current broken state
- [ ] Rewrite the expression below so that the package list is returned

I can do this next week, or on the plane back but if either of you have time this I'm happy for a PR (no obligation).

**Comment by richfitz** [comment]
Thanks for reporting - should be fixed now :rocket:

**Comment by aammd** [comment]
i  can confirm that it works as desired now. 
Question: how do you guys see this feature being used? Is it to reach out to people who are uncomfortable reading yaml?

**Comment by dfalster** [comment]
Sweet, thanks for fixing!

**Comment by dfalster** [comment]
Works here too!

Currently I’m using it as a bridge to ease transition in a project from not
using to using remake

Can also be useful for reproducibility - if someone doesn’t feel
comfortable with remake you might just give them the Rscript.

**Comment by richfitz** [comment]
I implemented this so that people never felt they were commited to remake; that they could easily move from remake to a traditional r analysis. I don't like the idea of tools that lock you into a particular way of working.
