### ISSUE TITLE
dump_environment() bug

### ISSUE THREAD

**Issue by wcornwell** [richfitz/remake#78]
Hard to give reproducible examples for entire remake workflows, but I have a project that make() successfully, but using dump_environment() has this problem:

```{R}
> remake::dump_environment()
[  LOAD ] 
[  READ ]                                        |  # loading sources
[  DUMP ] 
Error in rawToChar(as.raw(x)) : embedded nul in string: 's\a\0\x99\xaa@'
In addition: Warning messages:
1: package ‘htmlTable’ was built under R version 3.2.3 
2: package ‘rworldmap’ was built under R version 3.2.3 
3: package ‘ncdf4’ was built under R version 3.2.3 
4: In rawToChar(as.raw(x)) :
  out-of-range values treated as 0 in coercion to raw
```
any idea?  fetching all the pieces seems fine, so not sure how to find the bug more specifically.

**Comment by richfitz** [comment]
I presume this is a private repo?  Can you give me the result of `traceback()`?  To narrow it down we'll need to do some back and forth to get isolate the file that is being loaded that has the 

There's a good chance you've been hit by a breaking change in storr where I did restructure the database format[*] so if you've upgraded to storr 1.0.0 since running the analysis it's possible that something bad has happened there (devtools also upgrades packages when you run `install_github` which has bitten me a few times now).  The error you have there makes that likely.  Can you move the `.remake` directory out the way and try rebuilding/dumping.

[*] the issue is rds storage of objects which might contain names that are not valid filename characters -- now I base64 encode the object name wheras previously I hashed the object contents which was irreversible.  The new approach is better but it has broken things and I can't write a translation script because of the irreversibility.

**Comment by wcornwell** [comment]
```{R}
> traceback()
12: rawToChar(as.raw(x))
11: FUN(X[[i]], ...)
10: vapply(X, FUN, character(1), ...)
9: vcapply(x, decode64, char62, char63, USE.NAMES = FALSE)
8: decode64(ret, TRUE)
7: self$driver$list_keys(namespace)
6: sort(self$driver$list_keys(namespace))
5: src$list(namespace)
4: storr_copy(dest, self, list, namespace)
3: obj$store$objects$export(envir)
2: remake_dump_environment(obj, envir)
1: remake::dump_environment()
```

**Comment by wcornwell** [comment]
I think you got it.  

Moving the .remake directory out and rebuilding/dumping worked!
